server:
  port: 9999
  eureka:
    client:
      serviceUrl:
        defaultZone: http://localhost:8761/eureka/
spring:
  cloud:
    gateway:
      routes:
        - id: product-service
          uri: http://localhost:8080/
          predicates:
            - Path: /user/
            - Path: /all/
  main:
    web-application-type: reactive
