server:
  port: 9999
  eureka:
    client:
      serviceUrl:
        defaultZone: http://localhost:8761/eureka/
spring:
  cloud:
    gateway:
      routes:
        - id: r1
          uri: http://localhost:8080/
  main:
    web-application-type: reactive
